# Configuration of Hugo
# Guide: https://wowchemy.com/docs/getting-started/
# Hugo Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

title: Führung in Transformation # Website name
baseURL: 'https://fuehrung.info/' # Website URL

params:
    author: Christian Renz
    description: '<![CDATA[
<p>Hallo! Ich bin Christian Renz.</p>
<p>Als Führungskraft ist es meine Leidenschaft, Menschen und Organisationen in die Erreichung
gemeinsamer Ziele zu führen und ihnen dabei zu helfen, sich weiter zu entwickeln. Besonders spannend
sind Zeiten des Umbruchs: Wo sich das Umfeld oder in der Organisation Dinge so stark entwickeln, dass die
bisherigen Vorgehensweisen nicht mehr tragen, muss sich die Organisation weiterentwickeln – sich in eine
neue Form transformieren. Dabei habe ich gelernt: Führung beginnt immer bei mir als Person.</p>

<p>In meinem Podcast treffe ich Menschen, die Transformation erleben und Menschen in der Transformation
führen. Ich möchte an ihren Erfahrungen teilhaben, mir Tips und Antworten auf konkrete Fragestellungen
holen und mich von ihnen als Personen inspirieren lassen.</p>
]]>
'
    iTunes_Category: 'Business'
    iTunes_Subcategory: 'Management'
    iTunes_Artwork: 'images/fuehrung_in_transformation_artwork.jpg'
    iTunes_EMail: 'feedback@fuehrung.info'


############################
## LANGUAGE
############################

defaultContentLanguage: de
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

############################
## MODULES
############################

module:
  imports:
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy-cms/v5
    - path: github.com/wowchemy/wowchemy-hugo-modules/wowchemy/v5
# Make static files available within assets
  mounts:
    - source: static
      target: assets/static

############################
## ADVANCED
############################

enableGitInfo: false
summaryLength: 30
paginate: 10
enableEmoji: true
enableRobotsTXT: true
footnotereturnlinkcontents: <sup>^</sup>
ignoreFiles: [\.ipynb$, .ipynb_checkpoints$, \.Rmd$, \.Rmarkdown$, _cache$]
permalinks:
  episode: '/episode/:slug/'
#  event: '/talk/:slug/'
#  tags: '/tag/:slug/'
#  categories: '/category/:slug/'
#  publication_types: '/publication-type/:slug/'
disableAliases: true
outputs:
#  home: [] # [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  home: [HTML, RSS, JSON, WebAppManifest, headers, redirects]
  section: [HTML, RSS]
imaging:
  resampleFilter: lanczos
  quality: 75
  anchor: smart
timeout: 600000
taxonomies:
  tag: tags
  category: categories
  publication_type: publication_types
  author: authors
markup:
  _merge: deep
related:
  threshold: 80
  includeNewer: true
  toLower: true
  indices:
    - name: tags
      weight: 100
    - name: categories
      weight: 70
security:
  _merge: deep
sitemap:
  _merge: deep

# Configuration for episodes
cascade:
  - _target:
      path: /episode/**
    profile: false
    pager: true
    isEpisode: true
    image:
      placement: 1
      focal_point: "TopLeft"
      preview_only: false

